import { describe, expect, it } from "vitest";
import { type DeriveSeams, deriveFence } from "../src/derive.js";
import { serializeFenceFile } from "../src/fence-file.js";

const HEAD_BY_PATH: Record<string, string> = {
  "pnpm-lock.yaml": "lockfileVersion: '9.0'",
  "src/gen/api.ts": "// @generated by protoc-gen-ts — DO NOT EDIT\nexport const x = 1;",
  "src/app.ts": "export const app = 1;",
  "big.min.js": "", // stands in for the >1 MiB skip below via readFileHead → null
};

function seams(over: Partial<DeriveSeams> = {}): DeriveSeams {
  return {
    listTrackedFiles: () => Object.keys(HEAD_BY_PATH).sort(),
    readFileHead: (p) => (p === "big.min.js" ? null : (HEAD_BY_PATH[p] ?? null)),
    dirExists: (p) => ["dist", "vendor"].includes(p),
    readGitattributes: () =>
      "/src/gen/api.ts linguist-generated\nlegacy/[ab].ts linguist-generated\n",
    ...over,
  };
}

describe("deriveFence", () => {
  it("derives all five signal classes with reasons, sorted by path", () => {
    const out = deriveFence(seams());
    expect(out.file.entries).toEqual([
      {
        path: "dist/**",
        class: "build-output",
        reason: "derived: build-output dir on disk",
      },
      {
        path: "pnpm-lock.yaml",
        class: "lockfile",
        reason: "derived: lockfile basename",
      },
      {
        path: "src/gen/api.ts",
        class: "codegen-header",
        reason: 'derived: codegen header "@generated"',
      },
      {
        path: "vendor/**",
        class: "vendored",
        reason: "derived: vendored dir",
      },
    ]);
    expect(out.skipped).toEqual([
      {
        pattern: "legacy/[ab].ts",
        reason: "bracket expressions unsupported",
      },
    ]);
    expect(out.degradedSignals).toEqual([]);
  });
  it("first signal wins on a path double-hit (codegen beats gitattributes here)", () => {
    const out = deriveFence(seams());
    const gen = out.file.entries.filter((e) => e.path === "src/gen/api.ts");
    expect(gen).toHaveLength(1);
    expect(gen[0]?.class).toBe("codegen-header");
  });
  it("files over the size cap are skipped by the head seam, not scanned", () => {
    const out = deriveFence(seams());
    expect(out.file.entries.some((e) => e.path === "big.min.js")).toBe(false);
  });
  it("no git → fs-only signals, (c) and (d) reported degraded", () => {
    const out = deriveFence(seams({ listTrackedFiles: () => null }));
    expect(out.degradedSignals).toEqual(["codegen-header", "linguist-generated"]);
    expect(out.file.entries.some((e) => e.class === "codegen-header")).toBe(false);
    expect(out.file.entries.some((e) => e.path === "dist/**")).toBe(true);
  });
  it("derivation is deterministic: derive twice → byte-identical serialization", () => {
    const a = serializeFenceFile(deriveFence(seams()).file);
    const b = serializeFenceFile(deriveFence(seams()).file);
    expect(a).toBe(b);
  });
});
