import type { AgentId } from "@megasaver/shared";

export type HarnessCategory = "cli" | "ide" | "extension";

export interface HarnessExtensionDir {
  /** Home-relative parent directory, e.g. "~/.vscode/extensions". */
  readonly parent: string;
  /** Extension folder prefix without the version suffix, e.g. "saoudrizwan.claude-dev". */
  readonly prefix: string;
}

export interface HarnessDescriptor {
  readonly id: AgentId;
  readonly name: string;
  readonly category: HarnessCategory;
  readonly binaries: readonly string[];
  readonly configDirs: readonly string[];
  readonly extensionDirs: readonly HarnessExtensionDir[];
  readonly projectMarkers: readonly string[];
  /** Dedicated ConnectorTarget id this harness auto-configures through, or null. */
  readonly connectorTargetId: string | null;
  /**
   * Shared-file fallback for harnesses that read a file another target owns
   * (the AGENTS.md convention family), or null.
   */
  readonly coveredByTargetId: string | null;
}

// The 2026 popular-harness research set (spec 2026-08-26-harness-autodetect
// §3). 39 entries: 28 cli, 6 ide, 5 extension. Detection signals are
// conservative footprints — false negatives are acceptable, false positives
// are not. Project markers are UNIQUE per harness (critic F1): a shared
// convention file (AGENTS.md) proves nothing about which harness is
// installed, so only codex carries it; the AGENTS.md-family harnesses
// (goose, crush, amp, iflow, droid, warp, zed) detect via machine signals
// and fold onto the codex TARGET for configuration via coveredByTargetId.
export const HARNESS_CATALOG: readonly HarnessDescriptor[] = Object.freeze([
  // --- cli ---
  {
    id: "claude-code",
    name: "Claude Code",
    category: "cli",
    binaries: ["claude"],
    configDirs: ["~/.claude"],
    extensionDirs: [],
    projectMarkers: ["CLAUDE.md"],
    connectorTargetId: "claude-code",
    coveredByTargetId: null,
  },
  {
    id: "codex",
    name: "OpenAI Codex CLI",
    category: "cli",
    binaries: ["codex"],
    configDirs: ["~/.codex"],
    extensionDirs: [],
    projectMarkers: ["AGENTS.md"],
    connectorTargetId: "codex",
    coveredByTargetId: null,
  },
  {
    id: "gemini",
    name: "Gemini CLI",
    category: "cli",
    binaries: ["gemini"],
    configDirs: ["~/.gemini"],
    extensionDirs: [],
    projectMarkers: ["GEMINI.md"],
    connectorTargetId: "gemini",
    coveredByTargetId: null,
  },
  {
    id: "aider",
    name: "Aider",
    category: "cli",
    binaries: ["aider", "aider-chat"],
    configDirs: ["~/.aider"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: "aider",
    coveredByTargetId: null,
  },
  {
    id: "opencode",
    name: "OpenCode",
    category: "cli",
    binaries: ["opencode"],
    configDirs: ["~/.config/opencode"],
    extensionDirs: [],
    projectMarkers: [".opencode"],
    connectorTargetId: "opencode",
    coveredByTargetId: null,
  },
  {
    id: "goose",
    name: "Goose (Block)",
    category: "cli",
    binaries: ["goose"],
    configDirs: ["~/.config/goose"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: "codex",
  },
  {
    id: "crush",
    name: "Crush (Charm)",
    category: "cli",
    binaries: ["crush"],
    configDirs: ["~/.config/crush"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: "codex",
  },
  {
    id: "amazon-q",
    name: "Amazon Q Developer CLI",
    category: "cli",
    binaries: ["q", "aws-q"],
    configDirs: ["~/.aws/amazonq"],
    extensionDirs: [],
    projectMarkers: [".amazonq/rules"],
    connectorTargetId: "amazon-q",
    coveredByTargetId: null,
  },
  {
    id: "copilot",
    name: "GitHub Copilot CLI",
    category: "cli",
    binaries: ["copilot"],
    configDirs: ["~/.config/github-copilot"],
    extensionDirs: [{ parent: "~/.vscode/extensions", prefix: "github.copilot" }],
    projectMarkers: [".github/copilot-instructions.md"],
    connectorTargetId: "copilot",
    coveredByTargetId: null,
  },
  {
    id: "amp",
    name: "Amp (Sourcegraph)",
    category: "cli",
    binaries: ["amp"],
    configDirs: ["~/.config/amp"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: "codex",
  },
  {
    id: "qwen",
    name: "Qwen Code",
    category: "cli",
    binaries: ["qwen"],
    configDirs: ["~/.qwen"],
    extensionDirs: [],
    projectMarkers: ["QWEN.md"],
    connectorTargetId: "qwen",
    coveredByTargetId: null,
  },
  {
    id: "iflow",
    name: "iFlow CLI",
    category: "cli",
    binaries: ["iflow"],
    configDirs: ["~/.iflow"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: "codex",
  },
  {
    id: "plandex",
    name: "Plandex",
    category: "cli",
    binaries: ["plandex", "pdx"],
    configDirs: ["~/.plandex"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    category: "cli",
    binaries: ["openclaw", "clawdbot", "moltbot"],
    configDirs: ["~/.openclaw", "~/.clawdbot"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "droid",
    name: "Factory Droid",
    category: "cli",
    binaries: ["droid"],
    configDirs: ["~/.factory"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: "codex",
  },
  {
    id: "warp",
    name: "Warp",
    category: "cli",
    binaries: ["warp", "warp-agent"],
    configDirs: ["~/.warp"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: "codex",
  },
  {
    id: "deepseek",
    name: "DeepSeek CLI",
    category: "cli",
    binaries: ["deepseek", "deepseek-cli"],
    configDirs: ["~/.deepseek"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "hermes",
    name: "Hermes",
    category: "cli",
    binaries: ["hermes"],
    configDirs: ["~/.hermes"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "openhands",
    name: "OpenHands",
    category: "cli",
    binaries: ["openhands", "opendevin"],
    configDirs: ["~/.openhands"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "gptme",
    name: "gptme",
    category: "cli",
    binaries: ["gptme"],
    configDirs: ["~/.local/share/gptme"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "grok",
    name: "Grok CLI",
    category: "cli",
    binaries: ["grok", "grok-cli"],
    configDirs: [],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "bits",
    name: "Bits (bitmagic)",
    category: "cli",
    binaries: ["bits"],
    configDirs: [],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "tabby",
    name: "Tabby",
    category: "cli",
    binaries: ["tabby"],
    configDirs: ["~/.tabby"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "refact",
    name: "Refact.ai",
    category: "cli",
    binaries: ["refact"],
    configDirs: ["~/.refact"],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "cody",
    name: "Sourcegraph Cody",
    category: "cli",
    binaries: ["cody"],
    configDirs: [],
    extensionDirs: [{ parent: "~/.vscode/extensions", prefix: "sourcegraph.cody-ai" }],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "mentat",
    name: "Mentat",
    category: "cli",
    binaries: ["mentat"],
    configDirs: [],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "gpt-engineer",
    name: "GPT Engineer",
    category: "cli",
    binaries: ["gpte", "gpt-engineer"],
    configDirs: [],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "devin",
    name: "Devin CLI",
    category: "cli",
    binaries: ["devin"],
    configDirs: [],
    extensionDirs: [],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  // --- ide ---
  {
    id: "cursor",
    name: "Cursor",
    category: "ide",
    binaries: ["cursor", "cursor-agent"],
    configDirs: ["~/.cursor"],
    extensionDirs: [],
    projectMarkers: [".cursor/rules"],
    connectorTargetId: "cursor",
    coveredByTargetId: null,
  },
  {
    id: "windsurf",
    name: "Windsurf",
    category: "ide",
    binaries: ["windsurf"],
    configDirs: ["~/.codeium/windsurf", "~/.windsurf"],
    extensionDirs: [],
    projectMarkers: [".windsurfrules"],
    connectorTargetId: "windsurf",
    coveredByTargetId: null,
  },
  {
    id: "continue",
    name: "Continue",
    category: "ide",
    binaries: ["continue"],
    configDirs: ["~/.continue"],
    extensionDirs: [],
    projectMarkers: [".continue/rules"],
    connectorTargetId: "continue",
    coveredByTargetId: null,
  },
  {
    id: "zed",
    name: "Zed",
    category: "ide",
    binaries: ["zed"],
    configDirs: ["~/.zed"],
    extensionDirs: [],
    projectMarkers: [".zed"],
    connectorTargetId: null,
    coveredByTargetId: "codex",
  },
  {
    id: "trae",
    name: "Trae",
    category: "ide",
    binaries: ["trae"],
    configDirs: ["~/.trae"],
    extensionDirs: [],
    projectMarkers: [".trae/rules"],
    connectorTargetId: "trae",
    coveredByTargetId: null,
  },
  {
    id: "antigravity",
    name: "Google Antigravity",
    category: "ide",
    binaries: [],
    configDirs: ["~/.antigravity"],
    extensionDirs: [],
    projectMarkers: [".agent/rules"],
    connectorTargetId: "antigravity",
    coveredByTargetId: null,
  },
  // --- extension ---
  {
    id: "cline",
    name: "Cline",
    category: "extension",
    binaries: [],
    configDirs: [],
    extensionDirs: [{ parent: "~/.vscode/extensions", prefix: "saoudrizwan.claude-dev" }],
    projectMarkers: [".clinerules"],
    connectorTargetId: "cline",
    coveredByTargetId: null,
  },
  {
    id: "roo-code",
    name: "Roo Code",
    category: "extension",
    binaries: [],
    configDirs: [],
    extensionDirs: [{ parent: "~/.vscode/extensions", prefix: "rooveterinaryinc.roo-cline" }],
    projectMarkers: [".roo"],
    connectorTargetId: "roo-code",
    coveredByTargetId: null,
  },
  {
    id: "kilo-code",
    name: "Kilo Code",
    category: "extension",
    binaries: [],
    configDirs: [],
    extensionDirs: [{ parent: "~/.vscode/extensions", prefix: "kilocode.kilo-code" }],
    projectMarkers: [".kilocode/rules"],
    connectorTargetId: "kilo-code",
    coveredByTargetId: null,
  },
  {
    id: "qodo",
    name: "Qodo Gen",
    category: "extension",
    binaries: [],
    configDirs: [],
    extensionDirs: [{ parent: "~/.vscode/extensions", prefix: "qodo.qodo-gen" }],
    projectMarkers: [],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
  {
    id: "avante",
    name: "avante.nvim",
    category: "extension",
    binaries: [],
    configDirs: [],
    extensionDirs: [{ parent: "~/.local/share/nvim/lazy", prefix: "avante.nvim" }],
    projectMarkers: [".avante/rules"],
    connectorTargetId: null,
    coveredByTargetId: null,
  },
]);
