import { describe, expect, it } from "vitest";
import { MAX_REFS_PER_EDIT, PACKAGE_SCAN_CAP, extractPackageRefs } from "../src/package-refs.js";

// Figures regenerated by scripts/package-refs-redos-probe.mjs (committed
// harness). Fixed code, 2026-08-15: every shape ~3.84-3.95x from n to 4n,
// per-call cost ≤ 0.19ms at the shipped cap. Revert drill (same probe,
// capture widened to `([^"']*[\w./-]+)+` with the closing quote REQUIRED):
// the probe did not finish within 90s — pathological. Ceiling 1000ms sits in
// the ~5000x separation gap, tail-safe, `retry: 3` (session-hints precedent:
// ratios cried wolf on windows-latest; ceilings at the shipped cap did not).
const CEILING_MS = 1_000;
const npmSource = { kind: "source", ecosystem: "npm" } as const;

const elapsed = (run: () => void): number => {
  const started = performance.now();
  run();
  return performance.now() - started;
};

const SHAPES: ReadonlyArray<readonly [string, (size: number) => string]> = [
  ["an unclosed from-specifier flood", (s) => 'from "a'.repeat(Math.ceil(s / 7)).slice(0, s)],
  ["a single repeated word char", (s) => "x".repeat(s)],
  ["an unclosed require-call flood", (s) => "require('p".repeat(Math.ceil(s / 10)).slice(0, s)],
] as const;

describe("extractPackageRefs — ReDoS regression at the shipped scan cap", () => {
  for (const [label, shape] of SHAPES) {
    it(`scans ${PACKAGE_SCAN_CAP} chars of ${label} under ${CEILING_MS}ms`, { retry: 3 }, () => {
      const input = shape(PACKAGE_SCAN_CAP);
      expect(elapsed(() => extractPackageRefs(npmSource, input))).toBeLessThan(CEILING_MS);
    });
  }
});

describe("structural pins (deterministic halves of the fence)", () => {
  // Pins the {1,300} bound: a 301-char specifier must NOT match. The only
  // bound-preserving regression left is a quantifier widen, which the ceiling
  // catches; together the halves cover both revert paths (session-hints:59-62).
  it("rejects a specifier longer than 300 chars", () => {
    const spec = "a".repeat(301);
    expect(extractPackageRefs(npmSource, `import x from "${spec}";`)).toEqual([]);
  });
  // Non-vacuity (redos-guard-testing: "assert a minimum match count before
  // asserting anything about what a corpus produced").
  it("the adversarial suite is not vacuous: a realistic corpus still extracts", () => {
    const corpus = Array.from({ length: 200 }, (_, i) => `import x${i} from "pkg-${i}";`).join(
      "\n",
    );
    expect(extractPackageRefs(npmSource, corpus)).toHaveLength(MAX_REFS_PER_EDIT);
  });
});
