export {
  runOutputPipeline,
  type RunOutputInput,
  type RunOutputResult,
  runOutputExecCommand,
  type RunOutputExecInput,
  type RunOutputExecResult,
  type RunCommandSpawn,
  type ExecResult,
  fetchChunk,
  type FetchChunkResult,
  locateChunkSet,
  type LocatedChunkSet,
  resolveEffectiveSettings,
  runTwoGates,
  readAndFilter,
  persistChunkSet,
  recordAndFilterOverlayOutput,
  type RecordOverlayOutputInput,
  type RecordOverlayOutputResult,
  defaultNow,
  defaultNewId,
  type EffectiveSettings,
  type GateResult,
  type PipelineEnv,
  type OrchestratorRegistry,
  type SessionView,
  type ProjectView,
  hashPath,
  loadReadIndex,
  type ReadIndexEntry,
} from "@megasaver/context-gate";
// Token-saver stats surface: the CLI reads session savings through core
// (§3c allow-list — apps/cli depends on core, never on @megasaver/stats
// directly; see apps/cli/test/dependency-graph.test.ts).
export {
  type AdoptionMetrics,
  aggregateAdoption,
  appendEvent,
  type AppendEventInput,
  type BuildProxyMetricsInput,
  buildProxyMetrics,
  computeInterception,
  HOOK_MISSING_HINT,
  type HookIngestResult,
  ingestHookLog,
  type InterceptionMetrics,
  type ProxyMetrics,
  type ProxyToolName,
  proxyToolNameForSourceKind,
  readEvents,
  readSummary,
  type SessionTokenSaverStats,
  StatsError,
  type StatsErrorCode,
  type StatsStore,
  type TokenSaverEvent,
} from "@megasaver/stats";

export {
  appendCodeTruthEvent,
  appendGuardEvent,
  appendHandoffEvent,
  appendWarmStartEvent,
  readCodeTruthEvents,
  readGuardEvents,
  readHandoffEvents,
  readWarmStartEvents,
  type CodeTruthEvent,
  type GuardEvent,
  type HandoffEvent,
  type WarmStartEvent,
} from "@megasaver/stats";

export {
  appendAuditEvent,
  type AppendAuditEventInput,
  readAuditEvents,
  summarizeAudit,
  type SummarizeAuditOptions,
  auditEventSchema,
  type AuditEvent,
  auditSummarySchema,
  type AuditSummary,
  auditWindowSchema,
  type AuditWindow,
  resolveAuditWindow,
} from "@megasaver/stats";

export {
  aggregateHonestMetrics,
  measuredTokenCoverage,
  observationsFromEvents,
  readOverlayEvents,
  readOverlaySummary,
  readOverlaySummaryAnyWorkspace,
  reconcileOverlaySummaries,
  recordedEventsFromLogs,
  tokensFromBytes,
  proxyUsageSavings,
  sumBytesSavedSince,
  type HonestMetrics,
  type OverlaySessionTokenSaverStats,
  type OverlayTokenSaverEvent,
  type ProxyUsageSavings,
  type ProxyUsageTokenCounts,
  MODEL_LIST_PRICES,
  estimateSavedValue,
  type ValuedRow,
  type SavedValueEstimate,
} from "@megasaver/stats";

// 1.13 persistent budget: the CLI reads/writes stats/budget.json through core
// (same §3c allow-list rule as readEvents above).
export {
  budgetPath,
  budgetStatus,
  clearBudget,
  readBudget,
  storedBudgetSchema,
  type StoredBudget,
  writeBudget,
} from "@megasaver/stats";

export {
  INPUT_PRICE_PER_MTOK_USD,
  CONTEXT_WINDOW_TOKENS,
  SAVINGS_FOOTNOTE,
  savingsFootnote,
  formatDollarsSaved,
  computeSavingsHeadline,
  savingsHeadlineFromTokens,
  type SavingsHeadline,
  type SavingsHeadlineTotals,
  readWorkspaceTokenSaverTotals,
  type WorkspaceTokenSaverTotals,
  readAllWorkspaceTokenSaverTotals,
  type AllWorkspaceTokenSaverTotals,
} from "@megasaver/stats";

export {
  BELOW_FLOOR_CAVEAT,
  COMMAND_UNMEASURED_CAVEAT,
  DISCOVER_HOOK_MISSING_HINT,
  hookLogRowSchema,
  parseHookLogRows,
  scanExposure,
  type ExposureCause,
  type ExposureGroup,
  type ExposureReport,
  type ExposureScanInput,
  type HookLogRow,
  type MediatedEvent,
  type MediatedFold,
  type TopFile,
  readWorkspaceOverlayEvents,
} from "@megasaver/stats";

// C4 cost ledger: the CLI consumes the pure rollup only through core (§3c —
// apps/cli never depends on @megasaver/stats directly).
export {
  UNKNOWN_COST_BUCKET,
  buildCostLedger,
  costFacetSchema,
  type BuildCostLedgerInput,
  type CostFacet,
  type CostLedger,
  type CostLedgerGroup,
  type CostLedgerTotals,
  type CostSessionMeta,
  type SavingsReceipt,
  type SpendReceipt,
} from "@megasaver/stats";

// C1 budget circuit breaker: apps read/write token budgets through core (§3c allow-list rule as above).
export {
  TOKEN_BUDGET_LABEL_MAX,
  storedTokenBudgetsSchema,
  type StoredTokenBudgets,
  tokenBudgetsPath,
  readTokenBudgets,
  tokenBudgetsStatus,
  writeTokenBudgets,
  clearTokenBudgets,
  type BudgetScope,
  type EffectiveBudget,
  effectiveSessionBudget,
  BUDGET_WARN_RATIO,
  BUDGET_VARIANCE_MULTIPLE,
  BUDGET_VARIANCE_MIN_SAMPLES,
  type MeasuredBurn,
  foldMeasuredBurn,
  medianOf,
  type BudgetAnnouncements,
  type EvaluateBudgetInput,
  type BudgetEvaluation,
  evaluateBudget,
  tokenBudgetStateSchema,
  type TokenBudgetState,
  tokenBudgetStatePath,
  readTokenBudgetState,
  writeTokenBudgetState,
} from "@megasaver/stats";
