export {
  runOutputPipeline,
  type RunOutputInput,
  type RunOutputResult,
  runOutputExecCommand,
  type RunOutputExecInput,
  type RunOutputExecResult,
  type RunCommandSpawn,
  type ExecResult,
  fetchChunk,
  type FetchChunkResult,
  locateChunkSet,
  type LocatedChunkSet,
  resolveEffectiveSettings,
  runTwoGates,
  readAndFilter,
  persistChunkSet,
  recordAndFilterOverlayOutput,
  type RecordOverlayOutputInput,
  type RecordOverlayOutputResult,
  defaultNow,
  defaultNewId,
  type EffectiveSettings,
  type GateResult,
  type PipelineEnv,
  type OrchestratorRegistry,
  type SessionView,
  type ProjectView,
} from "@megasaver/context-gate";
// Token-saver stats surface: the CLI reads session savings through core
// (§3c allow-list — apps/cli depends on core, never on @megasaver/stats
// directly; see apps/cli/test/dependency-graph.test.ts).
export {
  type AdoptionMetrics,
  aggregateAdoption,
  appendEvent,
  type AppendEventInput,
  type BuildProxyMetricsInput,
  buildProxyMetrics,
  computeInterception,
  HOOK_MISSING_HINT,
  type HookIngestResult,
  ingestHookLog,
  type InterceptionMetrics,
  type ProxyMetrics,
  type ProxyToolName,
  proxyToolNameForSourceKind,
  readEvents,
  readSummary,
  type SessionTokenSaverStats,
  StatsError,
  type StatsErrorCode,
  type StatsStore,
  type TokenSaverEvent,
} from "@megasaver/stats";

export {
  appendAuditEvent,
  type AppendAuditEventInput,
  readAuditEvents,
  summarizeAudit,
  type SummarizeAuditOptions,
  auditEventSchema,
  type AuditEvent,
  auditSummarySchema,
  type AuditSummary,
  auditWindowSchema,
  type AuditWindow,
  resolveAuditWindow,
} from "@megasaver/stats";

export {
  aggregateHonestMetrics,
  observationsFromEvents,
  readOverlayEvents,
  readOverlaySummaryAnyWorkspace,
  recordedEventsFromLogs,
  tokensFromBytes,
  proxyUsageSavings,
  sumBytesSavedSince,
  type HonestMetrics,
  type OverlaySessionTokenSaverStats,
  type OverlayTokenSaverEvent,
  type ProxyUsageSavings,
  type ProxyUsageTokenCounts,
} from "@megasaver/stats";

export {
  INPUT_PRICE_PER_MTOK_USD,
  CONTEXT_WINDOW_TOKENS,
  SAVINGS_FOOTNOTE,
  savingsFootnote,
  computeSavingsHeadline,
  savingsHeadlineFromTokens,
  type SavingsHeadline,
  type SavingsHeadlineTotals,
  readWorkspaceTokenSaverTotals,
  type WorkspaceTokenSaverTotals,
  readAllWorkspaceTokenSaverTotals,
  type AllWorkspaceTokenSaverTotals,
} from "@megasaver/stats";
