// Order: alphabetic (AA3 convention). Exhaustive for v1.
// New codes require this list to grow + a fresh .test-d.ts assertion update.
// Mirrored in apps/gui/bridge/server.ts (bridge side).
export const BRIDGE_ERROR_CODES = [
  "bad_recovery_code",
  "brain_sync_not_configured",
  "claude_session_not_found",
  "conditional_writes_unsupported",
  "config_invalid",
  "connector_write_failed",
  "decrypt_failed",
  "event_not_found",
  "hash_mismatch",
  "index_unavailable",
  "insecure_endpoint",
  "internal_error",
  "keyfile_invalid",
  "keyfile_missing",
  "manifest_invalid",
  "mcp_setup_failed",
  "memory_entry_not_found",
  "method_not_allowed",
  "object_missing",
  "office_not_configured",
  "office_not_found",
  "origin_forbidden",
  "payment_required",
  "policy_load_failed",
  "precondition_failed",
  "pro_required",
  "project_not_found",
  "rollback_detected",
  "rootpath_invalid",
  "route_not_found",
  "session_already_ended",
  "session_not_found",
  "session_project_mismatch",
  "store_write_failed",
  "sync_conflict",
  "transport_error",
  "unauthorized",
  "validation_failed",
  "wrong_key",
] as const;
export type BridgeErrorCode = (typeof BRIDGE_ERROR_CODES)[number];

// Human-readable copy map used by ErrorState component.
// Falls back to the bridge's `error` string field for unknown codes.
export const BRIDGE_ERROR_COPY: Record<BridgeErrorCode, string> = {
  claude_session_not_found: "Claude Code session not found. It may have been removed.",
  connector_write_failed:
    "Could not write the workspace file. It may be a symlink or permission-protected.",
  event_not_found: "Event not found, or it has no stored output.",
  index_unavailable:
    "The semantic index is missing or corrupt. Rebuild it with `mega index build`.",
  internal_error: "Something went wrong. Try again.",
  mcp_setup_failed: "Agent setup failed. Check permissions and try again.",
  memory_entry_not_found: "Memory entry not found. It may have been removed.",
  method_not_allowed: "Request method not allowed.",
  office_not_configured: "Office is not configured. Server is missing office deps.",
  office_not_found: "Office resource not found. It may have been removed.",
  origin_forbidden: "Request blocked by the bridge origin policy.",
  policy_load_failed:
    "Permissions file is malformed. Fix .megasaver/permissions.yaml and try again.",
  project_not_found: "Project not found. It may have been removed.",
  rootpath_invalid: "Root path must be an existing, readable directory.",
  route_not_found: "API route not found.",
  session_already_ended: "This session has already ended.",
  session_not_found: "Session not found. It may have been removed.",
  session_project_mismatch: "Session does not belong to this project.",
  store_write_failed: "Store write failed. Check disk space and permissions.",
  unauthorized: "Missing or invalid bridge token.",
  validation_failed: "Invalid input. Check the highlighted fields and try again.",
  bad_recovery_code: "Recovery code is invalid. Check for typos.",
  brain_sync_not_configured: "Brain sync is not configured. Run `mega brain sync init`.",
  conditional_writes_unsupported: "Storage endpoint does not enforce conditional writes.",
  config_invalid: "Brain sync config is invalid or missing.",
  decrypt_failed: "Decryption failed — wrong key or corrupted data.",
  hash_mismatch: "Data hash mismatch — remote data is corrupt.",
  insecure_endpoint: "Endpoint must be https:// (http allowed only for localhost).",
  keyfile_invalid: "Keyfile is invalid or corrupted.",
  keyfile_missing: "Keyfile is missing. Run `mega brain sync init`.",
  manifest_invalid: "Remote manifest is invalid or corrupted.",
  object_missing: "Remote object not found — it may have been deleted.",
  precondition_failed: "Storage precondition failed — retry the operation.",
  rollback_detected: "Remote may have rolled back — reconciliation is required.",
  sync_conflict: "Sync conflict — another writer updated the remote. Retry.",
  transport_error: "Storage transport error — check endpoint and credentials.",
  wrong_key: "Stored key cannot decrypt the remote manifest — use the original recovery code.",
  payment_required:
    "Brain sync is a Mega Saver Pro feature. Activate a key: mega license activate <key>.",
  pro_required:
    "Brain sync is a Mega Saver Pro feature. Activate a key: mega license activate <key>.",
};
