import { describe, expect, it } from "vitest";
import { mcpToolNameSchema } from "../src/tool-name.js";

describe("tool-name enum (48 tools)", () => {
  it("is a closed set of 48 alphabetically-ordered names", () => {
    expect(mcpToolNameSchema.options).toEqual([
      "approve_memory",
      "audit_token_usage",
      "board_list",
      "board_post",
      "board_resolve",
      "build_task_plan",
      "check_approach",
      "convert_failure_to_rule",
      "explain_context_selection",
      "find_similar_failures",
      "get_applicable_rules",
      "get_context_budget_report",
      "get_edit_impact",
      "get_project_context",
      "get_project_rules",
      "get_relevant_code_blocks",
      "get_relevant_context",
      "get_relevant_memories",
      "get_task_context",
      "get_task_status",
      "get_warm_start_brief",
      "mega_fetch_chunk",
      "mega_impact",
      "mega_index_memory",
      "mega_memory_from_session",
      "mega_memory_sweep",
      "mega_read_file",
      "mega_recall",
      "mega_run_command",
      "mesh_broadcast",
      "mesh_claim",
      "mesh_events",
      "mesh_peers",
      "mesh_poll",
      "mesh_query",
      "mesh_release",
      "mesh_send",
      "mesh_status_set",
      "proxy_search_code",
      "record_failed_attempt",
      "record_task_step",
      "review_pack",
      "retry_failed_step",
      "route_tools_for_task",
      "save_memory",
      "save_project_rule",
      "search_memory",
      "verify_memories",
    ]);
  });
});
