// Committed generator for packages/context-gate/src/data/{npm-top,pypi-top,python-stdlib}.ts.
// Dev-time network only — the committed curated arrays stand when this is not
// runnable. Usage: node scripts/firewall-seed.mjs
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA = join(HERE, "..", "packages", "context-gate", "src", "data");

const HEADER = "// generated by scripts/firewall-seed.mjs — do not hand-edit entries\n";

// Python stdlib: full CPython 3.12 sys.stdlib_module_names, embedded.
const STDLIB = [
  "__future__", "__main__", "_abc", "_aix_support", "_ast", "_asyncio", "_bisect",
  "_blake2", "_bootsubprocess", "_bz2", "_codecs", "_collections", "_collections_abc",
  "_compat_pickle", "_compression", "_contextvars", "_csv", "_ctypes", "_curses",
  "_datetime", "_decimal", "_elementtree", "_fractions", "_functools", "_gdbm",
  "_hashlib", "_heapq", "_imp", "_interpchannels", "_interpqueues", "_interpreters",
  "_io", "_json", "_locale", "_lsprof", "_lzma", "_markupbase", "_md5", "_multibytecodec",
  "_multiprocessing", "_opcode", "_operator", "_osx_support", "_overlapped", "_pickle",
  "_posixshmem", "_posixsubprocess", "_py_abc", "_pydatetime", "_pydecimal", "_pyio",
  "_pylong", "_queue", "_random", "_scproxy", "_sha1", "_sha2", "_sha3", "_signal",
  "_sitebuiltins", "_socket", "_sqlite3", "_sre", "_ssl", "_stat", "_statistics",
  "_string", "_strptime", "_struct", "_symtable", "_thread", "_threading_local",
  "_tkinter", "_tokenize", "_tracemalloc", "_typing", "_uuid", "_warnings", "_weakref",
  "_weakrefset", "_winapi", "_zoneinfo", "abc", "aifc", "argparse", "array", "ast",
  "asynchat", "asyncio", "asyncore", "atexit", "audioop", "base64", "bdb", "binascii",
  "bisect", "builtins", "bz2", "cProfile", "calendar", "cgi", "cgitb", "chunk", "cmath",
  "cmd", "code", "codecs", "codeop", "collections", "colorsys", "compileall",
  "concurrent", "configparser", "contextlib", "contextvars", "copy", "copyreg",
  "crypt", "csv", "ctypes", "curses", "dataclasses", "datetime", "dbm", "decimal",
  "difflib", "dis", "distutils", "doctest", "email", "encodings", "ensurepip", "enum",
  "errno", "faulthandler", "fcntl", "filecmp", "fileinput", "fnmatch", "fractions",
  "ftplib", "functools", "gc", "getopt", "getpass", "gettext", "glob", "grp", "gzip",
  "hashlib", "heapq", "hmac", "html", "http", "idlelib", "imaplib", "imghdr", "imp",
  "importlib", "inspect", "io", "ipaddress", "itertools", "json", "keyword", "lib2to3",
  "linecache", "locale", "logging", "lzma", "mailbox", "mailcap", "marshal", "math",
  "mimetypes", "mmap", "modulefinder", "msilib", "msvcrt", "multiprocessing", "netrc",
  "nis", "nntplib", "nt", "ntpath", "nturl2path", "numbers", "opcode", "operator",
  "optparse", "os", "ossaudiodev", "pathlib", "pdb", "pickle", "pickletools", "pipes",
  "pkgutil", "platform", "plistlib", "poplib", "posix", "posixpath", "pprint",
  "profile", "pstats", "pty", "pwd", "py_compile", "pyclbr", "pydoc", "queue", "quopri",
  "random", "re", "readline", "reprlib", "resource", "rlcompleter", "runpy", "sched",
  "secrets", "select", "selectors", "shelve", "shlex", "shutil", "signal", "site",
  "smtpd", "smtplib", "sndhdr", "socket", "socketserver", "spwd", "sqlite3", "ssl",
  "stat", "statistics", "string", "stringprep", "struct", "subprocess", "sunau",
  "symtable", "sys", "sysconfig", "syslog", "tabnanny", "tarfile", "telnetlib",
  "tempfile", "termios", "test", "textwrap", "threading", "time", "timeit", "tkinter",
  "token", "tokenize", "tomllib", "trace", "traceback", "tracemalloc", "tty", "turtle",
  "turtledemo", "types", "typing", "unicodedata", "unittest", "urllib", "uu", "uuid",
  "venv", "warnings", "wave", "weakref", "webbrowser", "winreg", "winsound", "wsgiref",
  "xdrlib", "xml", "xmlrpc", "zipapp", "zipfile", "zipimport", "zlib", "zoneinfo",
].sort();

const CURATED_NPM = [
  "@types/node", "axios", "chalk", "citty", "commander", "debug", "dotenv", "esbuild",
  "eslint", "execa", "express", "fastify", "glob", "inquirer", "jest", "koa",
  "left-pad", "lodash", "minimist", "mocha", "next", "node-fetch", "ora", "prettier",
  "react", "react-dom", "rollup", "rxjs", "semver", "svelte", "tslib", "typescript",
  "undici", "uuid", "vite", "vitest", "vue", "webpack", "ws", "yargs", "zod",
];

const CURATED_PYPI = [
  "aiohttp", "attrs", "beautifulsoup4", "boto3", "botocore", "certifi",
  "charset-normalizer", "click", "cryptography", "django", "fastapi", "flask",
  "httpx", "idna", "jinja2", "lxml", "markupsafe", "matplotlib", "numpy",
  "opencv-python", "packaging", "pandas", "pillow", "pip", "pydantic", "pytest",
  "python-dateutil", "pyyaml", "requests", "rich", "scikit-learn", "scipy",
  "setuptools", "six", "sqlalchemy", "tqdm", "typing-extensions", "urllib3",
  "uvicorn", "wheel",
];

function renderArray(name, names) {
  return `${HEADER}export const ${name}: readonly string[] = [\n${names
    .map((n) => `  "${n}",`)
    .join("\n")}\n];\n`;
}

async function fetchNpmTop() {
  const collected = [];
  for (const from of [0, 250, 500, 750]) {
    const url = `https://registry.npmjs.org/-/v1/search?text=boost-exact:false&popularity=1.0&size=250&from=${from}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`npm search ${from} -> ${res.status}`);
    const body = await res.json();
    collected.push(...body.objects.map((o) => o.package.name));
  }
  return [...new Set(collected)].filter((n) => n.length <= 214).sort();
}

async function fetchPypiTop() {
  const url = "https://hugovk.github.io/top-pypi-packages/top-pypi-packages-30-days.min.json";
  const res = await fetch(url);
  if (!res.ok) throw new Error(`top-pypi ${res.status}`);
  const body = await res.json();
  return body.rows.slice(0, 1000).map((r) => r.project).sort();
}

async function main() {
  let npm = [...CURATED_NPM];
  let pypi = [...CURATED_PYPI];
  let npmNote = "offline fallback";
  let pypiNote = "offline fallback";
  try {
    npm = [...new Set([...npm, ...(await fetchNpmTop())])].sort();
    npmNote = "registry-expanded";
    writeFileSync(join(DATA, "npm-top.ts"), renderArray("NPM_TOP", npm));
  } catch (err) {
    console.error(`npm seed fetch failed (curated stands): ${err.message}`);
  }
  try {
    pypi = [...new Set([...pypi, ...(await fetchPypiTop())])].sort();
    pypiNote = "dataset-expanded";
    writeFileSync(join(DATA, "pypi-top.ts"), renderArray("PYPI_TOP", pypi));
  } catch (err) {
    console.error(`pypi seed fetch failed (curated stands): ${err.message}`);
  }
  console.error(`npm-top: ${npm.length} names (${npmNote})`);
  console.error(`pypi-top: ${pypi.length} names (${pypiNote})`);
  console.error("NOTE: python-stdlib.ts stays curated (full 3.12 list embedded in this script).");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
