import { INPUT_PRICE_PER_MTOK_USD, type TokenSaverEvent, tokensFromBytes } from "@megasaver/stats";
import { type FixMemoryFile, type FixSaverState, computeFixPlan } from "./fix.js";
import { type WasteHeadline, computeWasteBreakdown, computeWasteHeadline } from "./insights.js";

export interface TeardownCulprit {
  key: string;
  events: number;
  tokensReturned: number;
  avgTokensPerTurn: number;
  dollarsReturned: number;
  returnedShare: number;
}

export interface TeardownAdvice {
  title: string;
  command: string | null;
}

export interface TeardownReport {
  headline: WasteHeadline;
  savedTokens: number;
  savedDollars: number;
  culprits: TeardownCulprit[];
  advice: TeardownAdvice[];
}

const TOP_CULPRITS = 5;

function dollarsFromTokens(tokens: number): number {
  return (tokens / 1_000_000) * INPUT_PRICE_PER_MTOK_USD;
}

export function composeTeardown(
  events: readonly TokenSaverEvent[],
  opts: { saver: FixSaverState | null; memoryFiles: readonly FixMemoryFile[] },
): TeardownReport {
  const headline = computeWasteHeadline(events);
  const savedTokens = tokensFromBytes(headline.totalBytesSaved);
  const culprits = computeWasteBreakdown(events, { by: "source" })
    .sort((a, b) => b.returnedShare - a.returnedShare || (a.key < b.key ? -1 : 1))
    .slice(0, TOP_CULPRITS)
    .map((r) => ({
      key: r.key,
      events: r.events,
      tokensReturned: r.tokensReturned,
      avgTokensPerTurn: Math.round(r.tokensReturned / r.events),
      dollarsReturned: r.dollarsReturned,
      returnedShare: r.returnedShare,
    }));
  // The exposé's treatment list ends with the one-command fix: appliable
  // actions collapse to `mega savings fix --apply`; advice keeps its command.
  const advice = computeFixPlan(events, opts).actions.map((a) => ({
    title: a.title,
    command: a.appliable ? "mega savings fix --apply" : a.command,
  }));
  return {
    headline,
    savedTokens,
    savedDollars: dollarsFromTokens(savedTokens),
    culprits,
    advice,
  };
}

function pct(n: number): string {
  return `${Math.round(n * 100)}%`;
}

function money(n: number): string {
  return `$${n.toFixed(2)} (est.)`;
}

function compactTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return `${Math.round(n)}`;
}

export function renderTeardownMarkdown(report: TeardownReport): string {
  const lines: string[] = [];
  lines.push("# Where the tokens went — a Mega Saver teardown");
  lines.push("");
  lines.push(
    "> Generated by `mega teardown` · figures are measured from this workspace's recorded tool events, not modeled",
  );
  lines.push("");
  lines.push("## The bill");
  lines.push("");
  if (report.headline.totalReturnedBytes === 0) {
    lines.push("No recorded events yet — run some sessions with the saver active and come back.");
  } else {
    lines.push(
      `Tool output returned into context: **${compactTokens(report.headline.tokensReturned)} tokens ≈ ${money(report.headline.dollarsReturned)}**.`,
    );
  }
  lines.push("");
  lines.push("## The culprits");
  lines.push("");
  if (report.culprits.length === 0) {
    lines.push("No recorded events yet.");
  } else {
    lines.push("| source | events | avg tokens/turn | share | $ (est.) |");
    lines.push("|---|---|---|---|---|");
    for (const c of report.culprits) {
      lines.push(
        `| ${c.key} | ${c.events} | ~${compactTokens(c.avgTokensPerTurn)} | ${pct(c.returnedShare)} | ${money(c.dollarsReturned)} |`,
      );
    }
  }
  lines.push("");
  lines.push("## What Mega Saver clawed back");
  lines.push("");
  lines.push(
    `**${compactTokens(report.savedTokens)} tokens ≈ ${money(report.savedDollars)}** never reached the context window (evidence-preserving compression — the originals stay recoverable).`,
  );
  lines.push("");
  lines.push("## The treatments");
  lines.push("");
  if (report.advice.length === 0) {
    lines.push("Nothing to fix — this workspace is already tight.");
  } else {
    for (const a of report.advice) {
      lines.push(a.command === null ? `- ${a.title}` : `- ${a.title} — \`${a.command}\``);
    }
  }
  lines.push("");
  lines.push("## Methodology");
  lines.push("");
  lines.push(
    `Dollar figures use a flat $${INPUT_PRICE_PER_MTOK_USD}/MTok input price and are estimates. Token counts are byte-derived (≈4 bytes/token) from locally recorded events. Sources are generic kinds — no paths, project names, or file contents appear in this document.`,
  );
  lines.push("");
  return lines.join("\n");
}

// XML-escape replicated from stats' savings-card (not exported there); a
// culprit key crosses into SVG text nodes, so metacharacters must not break
// the document.
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const GROUND = "#f6f5f2";
const INK = "#17181a";
const MUTED = "#6b6c70";
const FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";

export function renderTeardownCardSvg(report: TeardownReport): string {
  const top = report.culprits[0];
  const topLine = top
    ? `${top.key} · ~${compactTokens(top.avgTokensPerTurn)} tokens/turn`
    : "no recorded events yet";
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">`,
    `  <rect width="1200" height="630" fill="${GROUND}"/>`,
    `  <text x="80" y="120" font-family="${FONT}" font-size="28" fill="${MUTED}">Where the tokens went — a Mega Saver teardown</text>`,
    `  <text x="80" y="300" font-family="${FONT}" font-size="120" font-weight="700" fill="${INK}">${esc(money(report.headline.dollarsReturned))}</text>`,
    `  <text x="80" y="360" font-family="${FONT}" font-size="30" fill="${MUTED}">returned into context · ${esc(compactTokens(report.headline.tokensReturned))} tokens</text>`,
    `  <text x="80" y="440" font-family="${FONT}" font-size="30" fill="${INK}">top culprit: ${esc(topLine)}</text>`,
    `  <text x="80" y="520" font-family="${FONT}" font-size="26" fill="${MUTED}">clawed back: ${esc(compactTokens(report.savedTokens))} tokens ≈ ${esc(money(report.savedDollars))}</text>`,
    `  <text x="80" y="580" font-family="${FONT}" font-size="20" fill="${MUTED}">measured, not modeled · generated by mega teardown</text>`,
    "</svg>",
    "",
  ].join("\n");
}
