export const LONG_MEMORY_PACKAGE = "@megasaver/long-memory";
export { createInMemoryLongMemoryStore, type LongMemoryStore } from "./store.js";
export { dispatchRpcLine } from "./rpc.js";
export { Lm2Error, lm2ErrorCodeSchema, type Lm2ErrorCode } from "./lm2-errors.js";
export {
  rankLm2Candidates,
  type Lm2RankClock,
  type Lm2RankResult,
  type RankLm2CandidatesInput,
} from "./lm2-ranker.js";
export type { Lm2RankVectorReader } from "./lm2-semantic-lane.js";
export {
  MAX_LM2_ADMITTED_MODELS,
  MAX_LM2_CANDIDATE_CORPUS_UTF8_BYTES,
  MAX_LM2_CANDIDATE_TEXT_CODE_UNITS,
  MAX_LM2_DIMENSIONS,
  MAX_LM2_INDEX_BATCH_TIMEOUT_MS,
  MAX_LM2_INDEX_RECORDS,
  MAX_LM2_QUERY_TIMEOUT_MS,
  embeddingEgressSchema,
  embeddingPurposeSchema,
  hybridReceiptSchema,
  lm2CandidateSchema,
  lm2IndexReceiptSchema,
  lm2IndexRequestSchema,
  lm2ProfileSchema,
  lm2RankRequestSchema,
  lm2RuntimeConfigSchema,
  modelDescriptorSchema,
  type EmbeddingEgress,
  type EmbeddingPort,
  type EmbeddingPurpose,
  type HybridReceipt,
  type HybridSemanticReason,
  type Lm2Candidate,
  type Lm2IndexReceipt,
  type Lm2IndexRequest,
  type Lm2Profile,
  type Lm2RankRequest,
  type Lm2RuntimeConfig,
  type ModelDescriptor,
  type RemoteEmbeddingApprovalPort,
} from "./lm2-model.js";
export {
  canonicalFloat32,
  embeddingInputDigest,
  modelDescriptorFingerprint,
  type Lm2Sha256,
} from "./lm2-identity.js";
export { Lm1Error, lm1ErrorCodeSchema, type Lm1ErrorCode } from "./lm1-errors.js";
export {
  LM1_SCHEMA_VERSION,
  MAX_LM1_ACTION_CODE_UNITS,
  MAX_LM1_EVIDENCE_IDS,
  MAX_LM1_RECALL_TASK_CODE_UNITS,
  MAX_LM1_RECALL_TOKEN_BUDGET,
  MAX_LM1_STATE_KEY_CODE_UNITS,
  MAX_LM1_TEXT_CODE_UNITS,
  lm1KindSchema,
  lm1RecordSchema,
  lm1RecallRequestSchema,
  prepareCapture,
  prepareCaptureInputSchema,
  preparedCaptureSchema,
  evidenceBindingResultSchema,
  evidenceEligibilityResultSchema,
  type EvidenceBinding,
  type EvidenceBindingPort,
  type EvidenceEligibility,
  type EvidenceEligibilityPort,
  type Lm1Kind,
  type Lm1RecallBundle,
  type Lm1RecallRequest,
  type Lm1Record,
  type Lm1Snapshot,
  type Lm1Transition,
  type PreparedCapture,
  type PrepareCaptureInput,
  type RedactionPort,
} from "./lm1-model.js";
export {
  canonicalCaptureDigest,
  deriveEvidenceBindingDigest,
  deriveLm1RecordId,
  type Sha256,
} from "./lm1-identity.js";
export {
  compareSnapshotsForCurrent,
  selectCurrentStateSnapshots,
  selectStructuralSnapshotLeaves,
} from "./lm1-state.js";
export { createLm1Runtime, type Lm1Runtime } from "./lm1-runtime.js";
export {
  createLm2Runtime,
  type Lm2CaptureService,
  type Lm2RecallBundle,
  type Lm2RecallRequest,
  type Lm2Runtime,
  type Lm2RuntimeInput,
} from "./lm2-runtime.js";
export {
  MAX_EVIDENCE_IDS,
  MAX_EVIDENCE_ID_LENGTH,
  MAX_OBSERVATION_TEXT_CHARS,
  MAX_RECALL_TASK_CHARS,
  MAX_RECALL_TOKEN_BUDGET,
  MAX_WORKSPACE_KEY_LENGTH,
  observationKindSchema,
  observationSchema,
  recallRequestSchema,
  recallItemSchema,
  receiptItemSchema,
  recallBundleSchema,
  rpcRequestSchema,
  rpcResponseSchema,
  type ObservationKind,
  type Observation,
  type RecallRequest,
  type RecallItem,
  type ReceiptItem,
  type RecallBundle,
  type RpcRequest,
  type RpcResponse,
} from "./model.js";
